version: 2
jobs:
  build_apk:
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download dependencies
          command: |
            chmod a+x ./gradlew
            ./gradlew androidDependencies
      - save_cache:
          paths:
            - .gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build release APK
          command: |
             ./gradlew :app:assembleRelease
      - run:
          name: Install aws cli
          command: |
            pip install awscli --upgrade --user
      - run:  
          name: Upload apk
          command: |
            ~/.local/bin/aws s3 cp app/build/outputs/apk/release/app-release-unsigned.apk s3://10kg/coffeebuzapks/customerapp
workflows:
  version: 2
  build_and_save_apk:
    jobs:
      - build_apk:
          context: prod
          filters:
            branches:
              only:
                - master